sudo: required
dist: trusty
group: edge
addons:
  apt:
    packages:
      - mysql-server-5.6
      - mysql-client-core-5.6
      - mysql-client-5.6
  hosts:
      - magento2.travis
language: php
php:
  - 7.0
  - 7.1
env:
  global:
    - COMPOSER_BIN_DIR=~/bin
    - MAGENTO_HOST_NAME="magento2.travis"
  matrix:
    - MAGENTO_VERSION=develop
    - MAGENTO_VERSION=2.1-develop
    - MAGENTO_VERSION=2.1 CODE_COVERAGE=1
    - MAGENTO_VERSION=2.1.3
    - MAGENTO_VERSION=2.1.7
    - MAGENTO_VERSION=2.2.0-preview
matrix:
  allow_failures:
    - env: MAGENTO_VERSION=develop
    - env: MAGENTO_VERSION=2.1-develop
    - env: MAGENTO_VERSION=2.2.0-preview
  exclude:
    - php: 7.1
      env: MAGENTO_VERSION=2.1-develop
    - php: 7.1
      env: MAGENTO_VERSION=2.1 CODE_COVERAGE=1
    - php: 7.1
      env: MAGENTO_VERSION=2.1.3
    - php: 7.1
      env: MAGENTO_VERSION=2.1.7
cache:
  apt: true
  directories: $HOME/.composer/cache
before_install: ./travis/before_install.sh
install: ./travis/install.sh
before_script: ./travis/before_script.sh
script: phpunit -c $HOME/build/magento2ce/dev/tests/integration/phpunit.xml.dist --testsuite Integration
after_success: ./travis/after_success.sh
